var data = [
  {
    ClientID: 30167,
    ClientName: "AETN UK",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30003,
    ClientName: "AHOLD",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30025,
    ClientName: "AKDN",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30037,
    ClientName: "Alisdair Beatti",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30147,
    ClientName: "Allen & Overy",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30144,
    ClientName: "ARadu",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30059,
    ClientName: "Aramco Overseas Company B.V",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30093,
    ClientName: "Arjun Saggi",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30193,
    ClientName: "AutoIWRATSMatchScore",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30189,
    ClientName: "AutoIWRATSMatchScoreV2",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30192,
    ClientName: "AutoIWRATSSuccessScore",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30190,
    ClientName: "AutoIWRATSTraining",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30191,
    ClientName: "AutoIWRSS",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30090,
    ClientName: "Avon Cosmetics",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30123,
    ClientName: "Bakkavor",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30157,
    ClientName: "Base Model Professional (en_GB)",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30016,
    ClientName: "BaseBuild10",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30149,
    ClientName: "BaseLibrary TimeToValue4",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30150,
    ClientName: "BaseLibrary TimeToValue5",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30060,
    ClientName: "BaseLibrary-GB-3",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30015,
    ClientName: "BAT",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30042,
    ClientName: "Boots",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30158,
    ClientName: "bp_RARE",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30159,
    ClientName: "bp_RARE",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30196,
    ClientName: "BRWBIWRTEST",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30153,
    ClientName: "BT-EU-UK-1",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30154,
    ClientName: "BT-EU-UK-2",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30156,
    ClientName: "BT-EU-UK-3",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30163,
    ClientName: "BT-EU-UK-4",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30164,
    ClientName: "BT-EU-UK-5",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30165,
    ClientName: "BT-EU-UK-6",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30166,
    ClientName: "BT-EU-UK-7",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30152,
    ClientName: "BT-EU-US-1",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30155,
    ClientName: "BT-EU-US-2",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30143,
    ClientName: "BWilliams",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30011,
    ClientName: "Cardiff University",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30089,
    ClientName: "CBRE",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30096,
    ClientName: "Chantelle Foley",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30024,
    ClientName: "Claire's Accessories",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30061,
    ClientName: "Clara Siewert",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30063,
    ClientName: "Clara Siewert",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30050,
    ClientName: "Continental",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30040,
    ClientName: "CSC - Audrey Finley-Day",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30053,
    ClientName: "CSC - KCzapla",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30052,
    ClientName: "CSC - KSingh",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30026,
    ClientName: "CSC- Pgrantham",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30017,
    ClientName: "CSC- Stuart Dempsey",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30023,
    ClientName: "CSC-Dominic Wainwright",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30033,
    ClientName: "Danfoss",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30047,
    ClientName: "DEMO-2XA_TEST",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 516,
    ClientName: "demo-intl",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30021,
    ClientName: "DOF",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30005,
    ClientName: "EDF",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30092,
    ClientName: "Emily Jennings",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30100,
    ClientName: "Emma MacDonald",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30182,
    ClientName: "EUDEMO1",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30183,
    ClientName: "EUDEMO2",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30184,
    ClientName: "EUDEMO3",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30107,
    ClientName: "eutalentsuitebws",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30109,
    ClientName: "Eutalentsuitedemo",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30108,
    ClientName: "eutalentsuitsqa",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30099,
    ClientName: "Fariborz Karimi",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30121,
    ClientName: "Ferring Pharmaceuticals",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30076,
    ClientName: "First Gulf Bank",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30058,
    ClientName: "Frontier Medex",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30106,
    ClientName: "GBS - Haile-Selassie Negga",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30101,
    ClientName: "GBS - Steve Ingram",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30128,
    ClientName: "Georgina Jackson",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30049,
    ClientName: "Graphics Demo",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30168,
    ClientName: "Gullivers Travels",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30067,
    ClientName: "Hamad Bin Khalifa Medical City",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30078,
    ClientName: "Heineken UK",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30146,
    ClientName: "HEMA - Quebec",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30129,
    ClientName: "Henry Barker",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30009,
    ClientName: "Herbert Smith",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30004,
    ClientName: "Hornbach",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30077,
    ClientName: "HSS Hire Services Ltd",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30127,
    ClientName: "Ian Staal",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 26059,
    ClientName: "IBM",
    Active_DsnidDsnId: 8,
    PassiveDsnId: 8,
    Status: 1,
    LoginDsnId: 8,
    Active_Dsnid: 8,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_105",
    Login_DSNID: 8,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_105",
  },
  {
    ClientID: 30186,
    ClientName: "IBMEarlyAdopter",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30044,
    ClientName: "IC - Chris Wilson",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30038,
    ClientName: "IC - Pawel Musial",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30039,
    ClientName: "IC -Ashley Injore",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30051,
    ClientName: "IC-AStrugnell",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30035,
    ClientName: "IC-Chris Jeffrey",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30022,
    ClientName: "IC-MCross",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30072,
    ClientName: "IC-ndubois",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30071,
    ClientName: "IC-nhancox",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30031,
    ClientName: "IC-Phillip Green",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30036,
    ClientName: "IC-Robert Goulding",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30045,
    ClientName: "IC-RUSS AUGER",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30138,
    ClientName: "idpEUTestclient",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30084,
    ClientName: "Internal Kenexa - Beatrijs van Rickevorsel",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30086,
    ClientName: "Internal Kenexa - Chiara Staples",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30087,
    ClientName: "Internal Kenexa - Nina Boen",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30085,
    ClientName: "Internal Kenexa - Sarah Blackburn",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30074,
    ClientName: "Internal Test Site -Tommy Griffin",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30179,
    ClientName: "IWR Express",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30169,
    ClientName: "IWR Test Client",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30194,
    ClientName: "IWRMatchV2",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30091,
    ClientName: "Jennifer Aimer",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30013,
    ClientName: "Jet2",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30130,
    ClientName: "Joseph Saunderson",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30172,
    ClientName: "KAPSARC",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 0,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30131,
    ClientName: "Kay Buck",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30019,
    ClientName: "Kenexa Government Solutions",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30008,
    ClientName: "KPMG",
    Active_DsnidDsnId: 6,
    PassiveDsnId: 6,
    Status: 1,
    LoginDsnId: 6,
    Active_Dsnid: 6,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_104",
    Login_DSNID: 6,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_104",
  },
  {
    ClientID: 30007,
    ClientName: "KPMG-ELLP",
    Active_DsnidDsnId: 6,
    PassiveDsnId: 6,
    Status: 0,
    LoginDsnId: 6,
    Active_Dsnid: 6,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_104",
    Login_DSNID: 6,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_104",
  },
  {
    ClientID: 30083,
    ClientName: "Kuoni",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30010,
    ClientName: "Lend Lease",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30095,
    ClientName: "Lilliana Casallas",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30079,
    ClientName: "Linklaters Business Services",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30122,
    ClientName: "LMC International",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30139,
    ClientName: "LMedjidi",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30161,
    ClientName: "MHI",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30088,
    ClientName: "Mitrelli",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30002,
    ClientName: "Monitor101",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30135,
    ClientName: "Monitor101",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30134,
    ClientName: "Monitor102",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30014,
    ClientName: "Monitor103",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30006,
    ClientName: "Monitor104",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30125,
    ClientName: "Monitor105",
    Active_DsnidDsnId: 8,
    PassiveDsnId: 8,
    Status: 1,
    LoginDsnId: 8,
    Active_Dsnid: 8,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_105",
    Login_DSNID: 8,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_105",
  },
  {
    ClientID: 30162,
    ClientName: "Motorola Solutions",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30041,
    ClientName: "NATS",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30068,
    ClientName: "Novozymes",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30073,
    ClientName: "Nuffield Health",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30097,
    ClientName: "Olivia Cowdy",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 26536,
    ClientName: "OMGMonitor1",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30070,
    ClientName: "Omnicom",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30057,
    ClientName: "Paolo Byram",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30103,
    ClientName: "PC - Colin Dalton",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30104,
    ClientName: "PC - Joseph Williams",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30102,
    ClientName: "PC - Paul White",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30105,
    ClientName: "PC - Peter Morgan",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30132,
    ClientName: "PenTestClient One",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30133,
    ClientName: "PenTestClient Two",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30034,
    ClientName: "PM - Baldeep Kalsi",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30018,
    ClientName: "PM- Mary Cross",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30028,
    ClientName: "PM-Kevin Nally",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30032,
    ClientName: "PM-Roger Dale",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30055,
    ClientName: "Primark",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30075,
    ClientName: "Provident",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30056,
    ClientName: "PwC Global",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30136,
    ClientName: "QE Test TS1",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30137,
    ClientName: "QE Test TS2",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 12001,
    ClientName: "QEAPIAUTO1",
    Active_DsnidDsnId: 2,
    PassiveDsnId: 3,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 2,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101_SIKA",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 12002,
    ClientName: "QEAPIAUTO2",
    Active_DsnidDsnId: 2,
    PassiveDsnId: 3,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 2,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101_SIKA",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 12941,
    ClientName: "QEAUTO1",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 25464,
    ClientName: "QEAUTO10",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 25453,
    ClientName: "QEAUTO11",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 26552,
    ClientName: "QEAUTO14",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 16014,
    ClientName: "QEAUTO2",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 16029,
    ClientName: "QEAUTO3",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 20055,
    ClientName: "QEAUTO4",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 24000,
    ClientName: "QEAUTO5",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 25460,
    ClientName: "QEAUTO6",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 25461,
    ClientName: "QEAUTO7",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 25462,
    ClientName: "QEAUTO8",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 25217,
    ClientName: "QEAutoIntegration",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30174,
    ClientName: "Quest Global Engineering Services",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30094,
    ClientName: "Raji Nandipati",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30069,
    ClientName: "Razina Patel",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30043,
    ClientName: "Regus",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30062,
    ClientName: "Ryan MacDonald",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30177,
    ClientName: "Salutemyjob",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30145,
    ClientName: "Sandbox - Abdel Madjidi",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30110,
    ClientName: "Sandbox - Anders Larsen",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30142,
    ClientName: "Sandbox - EMEA Product Consultants",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30118,
    ClientName: "Sandbox - Gregory Kelly",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30120,
    ClientName: "Sandbox - Isabel Wray",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30111,
    ClientName: "Sandbox - Ivan Nicholls",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30116,
    ClientName: "Sandbox - Jonathan Khongwir",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30113,
    ClientName: "Sandbox - Katja B Jensen",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30140,
    ClientName: "Sandbox - Larisa Bouwer",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30119,
    ClientName: "Sandbox - Olivier Bancarel",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30112,
    ClientName: "Sandbox - Penelope Rammos",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30115,
    ClientName: "Sandbox - Priscilla MD Kortink",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30117,
    ClientName: "Sandbox - Richa Solanki",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30114,
    ClientName: "Sandbox - Sabine Eimbeck",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30141,
    ClientName: "Sandbox - Yang Sun",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 25270,
    ClientName: "Saudi Aramco",
    Active_DsnidDsnId: 5,
    PassiveDsnId: 5,
    Status: 1,
    LoginDsnId: 5,
    Active_Dsnid: 5,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_103",
    Login_DSNID: 5,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_103",
  },
  {
    ClientID: 30082,
    ClientName: "Saudi Aramco Local Recruitment",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30064,
    ClientName: "Saueressig",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30030,
    ClientName: "Shell",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30001,
    ClientName: "SIKA AG",
    Active_DsnidDsnId: 2,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 2,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101_SIKA",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30124,
    ClientName: "Solutec",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30046,
    ClientName: "Southern Water",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30181,
    ClientName: "STGTestclient",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30151,
    ClientName: "Straumann",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30148,
    ClientName: "Support_Kavya",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30180,
    ClientName: "SWF Admin Selenium",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30188,
    ClientName: "Swoop Talent",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30027,
    ClientName: "TC-HaydenMatthews",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30160,
    ClientName: "The Wellcome Trust",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30065,
    ClientName: "Tony Huckle",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30080,
    ClientName: "Total",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30081,
    ClientName: "Total_2",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30170,
    ClientName: "TrinaSolar",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30185,
    ClientName: "UNIQLO",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 0,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
  {
    ClientID: 30098,
    ClientName: "Vina Gami",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30171,
    ClientName: "Volvo Cars China",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 0,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30020,
    ClientName: "WBNetClient",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30012,
    ClientName: "WHSmith",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30048,
    ClientName: "YBS",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30054,
    ClientName: "Youngs",
    Active_DsnidDsnId: 3,
    PassiveDsnId: 4,
    Status: 1,
    LoginDsnId: 1,
    Active_Dsnid: 3,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_101",
    Login_DSNID: 1,
    Login_DB_server: "PEU-TDBCL01-00\\TGDB_00",
    Login_DB_name: "TGLogin",
  },
  {
    ClientID: 30195,
    ClientName: "Zain",
    Active_DsnidDsnId: 7,
    PassiveDsnId: 7,
    Status: 1,
    LoginDsnId: 7,
    Active_Dsnid: 7,
    Active_Dsnid_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Active_Dsnid_DB_name: "TG_Act_EU_102",
    Login_DSNID: 7,
    Login_DB_server: "PEU-TDBCL01-01\\TGDB_01",
    Login_DB_name: "TG_Act_EU_102",
  },
];
